version: '3.8'

services:
  unicloud-portal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "33999:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      # JWT 密钥（生产环境请使用更安全的密钥）
      - JWT_SECRET=portal_secret_key_unicloud
    volumes:
      # 如果需要持久化日志或其他数据，可以添加卷挂载
      - ./logs:/app/logs:rw
    restart: unless-stopped
    container_name: unicloud-portal
    networks:
      - unicloud-network

  # Nginx 作为反向代理
  nginx:
    image: nginx:alpine
    ports:
      - "19001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # 如果有 SSL 证书
      # - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - unicloud-portal
    restart: unless-stopped
    container_name: unicloud-nginx
    networks:
      - unicloud-network

networks:
  unicloud-network:
    driver: bridge

# 如果需要数据持久化
volumes:
  app_logs:
    driver: local
